openapi: 3.1.0
info:
  title: Member API
  description: 회원 도메인 API 명세
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: Auth
    description: 인증/인가
  - name: Member
    description: 회원 관리
  - name: Address
    description: 배송지 관리

paths:
  /auth/signup:
    post:
      tags: [Auth]
      summary: 회원 가입
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: 회원 가입 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponse'
        '400':
          description: 유효하지 않은 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 이메일 중복
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      tags: [Auth]
      summary: 로그인
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '423':
          description: 계정 잠금
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/refresh:
    post:
      tags: [Auth]
      summary: 토큰 갱신
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: 토큰 갱신 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: 유효하지 않은 Refresh Token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/logout:
    post:
      tags: [Auth]
      summary: 로그아웃
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '204':
          description: 로그아웃 성공

  /members/me:
    get:
      tags: [Member]
      summary: 내 정보 조회
      operationId: getMyInfo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberDetailResponse'
    patch:
      tags: [Member]
      summary: 내 정보 수정
      operationId: updateMyInfo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberUpdateRequest'
      responses:
        '200':
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberDetailResponse'

  /members/me/password:
    patch:
      tags: [Member]
      summary: 비밀번호 변경
      operationId: changePassword
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordChangeRequest'
      responses:
        '204':
          description: 비밀번호 변경 성공
        '400':
          description: 현재 비밀번호 불일치
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /members/me/withdraw:
    post:
      tags: [Member]
      summary: 회원 탈퇴
      operationId: withdraw
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
      responses:
        '204':
          description: 탈퇴 성공
        '400':
          description: 비밀번호 불일치
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /members/me/addresses:
    get:
      tags: [Address]
      summary: 배송지 목록 조회
      operationId: getAddresses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddressResponse'
    post:
      tags: [Address]
      summary: 배송지 추가
      operationId: addAddress
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressRequest'
      responses:
        '201':
          description: 배송지 추가 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressResponse'
        '400':
          description: 최대 배송지 개수 초과 (5개)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /members/me/addresses/{addressId}:
    parameters:
      - name: addressId
        in: path
        required: true
        schema:
          type: integer
          format: int64
    patch:
      tags: [Address]
      summary: 배송지 수정
      operationId: updateAddress
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressRequest'
      responses:
        '200':
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressResponse'
    delete:
      tags: [Address]
      summary: 배송지 삭제
      operationId: deleteAddress
      security:
        - bearerAuth: []
      responses:
        '204':
          description: 삭제 성공
        '400':
          description: 기본 배송지는 삭제 불가
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /members/me/addresses/{addressId}/default:
    parameters:
      - name: addressId
        in: path
        required: true
        schema:
          type: integer
          format: int64
    post:
      tags: [Address]
      summary: 기본 배송지 설정
      operationId: setDefaultAddress
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 설정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SignupRequest:
      type: object
      required: [email, password, name, phone]
      properties:
        email:
          type: string
          format: email
          maxLength: 100
        password:
          type: string
          minLength: 8
          maxLength: 20
          description: 영문+숫자+특수문자 조합
        name:
          type: string
          minLength: 2
          maxLength: 50
        phone:
          type: string
          pattern: '^01[0-9]-[0-9]{3,4}-[0-9]{4}$'

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    RefreshRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string

    TokenResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresIn:
          type: integer
          description: Access Token 만료 시간 (초)

    MemberResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time

    MemberDetailResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        name:
          type: string
        phone:
          type: string
        grade:
          $ref: '#/components/schemas/MemberGrade'
        totalPurchaseAmount:
          type: integer
          format: int64
          description: 누적 구매 금액
        createdAt:
          type: string
          format: date-time

    MemberGrade:
      type: string
      enum: [BRONZE, SILVER, GOLD, VIP]

    MemberUpdateRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 50
        phone:
          type: string
          pattern: '^01[0-9]-[0-9]{3,4}-[0-9]{4}$'

    PasswordChangeRequest:
      type: object
      required: [currentPassword, newPassword]
      properties:
        currentPassword:
          type: string
        newPassword:
          type: string
          minLength: 8
          maxLength: 20

    WithdrawRequest:
      type: object
      required: [password]
      properties:
        password:
          type: string

    AddressRequest:
      type: object
      required: [alias, recipientName, recipientPhone, zipCode, address, addressDetail]
      properties:
        alias:
          type: string
          maxLength: 20
          description: 배송지 별칭 (예: 집, 회사)
        recipientName:
          type: string
          maxLength: 50
        recipientPhone:
          type: string
          pattern: '^01[0-9]-[0-9]{3,4}-[0-9]{4}$'
        zipCode:
          type: string
          pattern: '^[0-9]{5}$'
        address:
          type: string
          maxLength: 200
        addressDetail:
          type: string
          maxLength: 100
        isDefault:
          type: boolean
          default: false

    AddressResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        alias:
          type: string
        recipientName:
          type: string
        recipientPhone:
          type: string
        zipCode:
          type: string
        address:
          type: string
        addressDetail:
          type: string
        isDefault:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
