openapi: 3.1.0
info:
  title: Order API
  description: 주문 도메인 API 명세
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: Order
    description: 주문 관리

paths:
  /orders:
    get:
      tags: [Order]
      summary: 내 주문 목록 조회
      operationId: getMyOrders
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/OrderStatus'
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
        - name: page
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderSliceResponse'
    post:
      tags: [Order]
      summary: 주문 생성
      operationId: createOrder
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
      responses:
        '201':
          description: 주문 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: 유효하지 않은 요청 (재고 부족 등)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 재고 충돌 (재시도 필요)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders/{orderNumber}:
    parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
          pattern: '^ORD-[0-9]{8}-[0-9]{6}$'
    get:
      tags: [Order]
      summary: 주문 상세 조회
      operationId: getOrder
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetailResponse'
        '403':
          description: 접근 권한 없음 (타인의 주문)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 주문 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders/{orderNumber}/cancel:
    parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
    post:
      tags: [Order]
      summary: 주문 취소
      operationId: cancelOrder
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCancelRequest'
      responses:
        '200':
          description: 취소 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: 취소 불가 상태 (배송 중 등)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders/{orderNumber}/confirm:
    parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
    post:
      tags: [Order]
      summary: 구매 확정
      operationId: confirmOrder
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 확정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: 확정 불가 상태
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    OrderStatus:
      type: string
      enum: [PENDING, PAID, PREPARING, SHIPPING, DELIVERED, CONFIRMED, CANCELLED]
      description: |
        - PENDING: 결제 대기
        - PAID: 결제 완료
        - PREPARING: 상품 준비중
        - SHIPPING: 배송중
        - DELIVERED: 배송 완료
        - CONFIRMED: 구매 확정
        - CANCELLED: 취소됨

    OrderCreateRequest:
      type: object
      required: [items, shippingAddress]
      properties:
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItemRequest'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddressRequest'
        couponId:
          type: integer
          format: int64
          description: 적용할 쿠폰 ID (선택)
        orderMemo:
          type: string
          maxLength: 200
          description: 주문 메모

    OrderItemRequest:
      type: object
      required: [productId, quantity]
      properties:
        productId:
          type: integer
          format: int64
        productOptionId:
          type: integer
          format: int64
          description: 옵션 ID (옵션 상품인 경우 필수)
        quantity:
          type: integer
          minimum: 1
          maximum: 99

    ShippingAddressRequest:
      type: object
      required: [recipientName, recipientPhone, zipCode, address, addressDetail]
      properties:
        recipientName:
          type: string
          maxLength: 50
        recipientPhone:
          type: string
          pattern: '^01[0-9]-[0-9]{3,4}-[0-9]{4}$'
        zipCode:
          type: string
          pattern: '^[0-9]{5}$'
        address:
          type: string
          maxLength: 200
        addressDetail:
          type: string
          maxLength: 100

    OrderCancelRequest:
      type: object
      required: [reason]
      properties:
        reason:
          type: string
          maxLength: 500

    OrderResponse:
      type: object
      properties:
        orderNumber:
          type: string
        status:
          $ref: '#/components/schemas/OrderStatus'
        totalAmount:
          type: integer
        discountAmount:
          type: integer
        shippingFee:
          type: integer
        finalAmount:
          type: integer
        createdAt:
          type: string
          format: date-time

    OrderDetailResponse:
      type: object
      properties:
        orderNumber:
          type: string
        status:
          $ref: '#/components/schemas/OrderStatus'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponse'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddressResponse'
        totalAmount:
          type: integer
          description: 상품 총액
        discountAmount:
          type: integer
          description: 쿠폰 할인액
        shippingFee:
          type: integer
          description: 배송비
        finalAmount:
          type: integer
          description: 최종 결제 금액
        orderMemo:
          type: string
        payment:
          $ref: '#/components/schemas/PaymentSummary'
        coupon:
          $ref: '#/components/schemas/CouponSummary'
        createdAt:
          type: string
          format: date-time
        paidAt:
          type: string
          format: date-time
        cancelledAt:
          type: string
          format: date-time
        cancelReason:
          type: string

    OrderItemResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        productName:
          type: string
        productOptionId:
          type: integer
          format: int64
        optionName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: integer
        totalPrice:
          type: integer
        thumbnailUrl:
          type: string

    ShippingAddressResponse:
      type: object
      properties:
        recipientName:
          type: string
        recipientPhone:
          type: string
        zipCode:
          type: string
        address:
          type: string
        addressDetail:
          type: string

    PaymentSummary:
      type: object
      properties:
        paymentId:
          type: integer
          format: int64
        status:
          type: string
        method:
          type: string
        paidAt:
          type: string
          format: date-time

    CouponSummary:
      type: object
      properties:
        couponId:
          type: integer
          format: int64
        couponName:
          type: string
        discountAmount:
          type: integer

    OrderSliceResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/OrderSummaryResponse'
        hasNext:
          type: boolean
        size:
          type: integer
        number:
          type: integer

    OrderSummaryResponse:
      type: object
      properties:
        orderNumber:
          type: string
        status:
          $ref: '#/components/schemas/OrderStatus'
        itemCount:
          type: integer
          description: 주문 상품 종류 수
        firstItemName:
          type: string
          description: 대표 상품명
        firstItemThumbnail:
          type: string
        finalAmount:
          type: integer
        createdAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
