openapi: 3.1.0
info:
  title: Payment API
  description: 결제 도메인 API 명세
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: Payment
    description: 결제 처리

paths:
  /payments:
    post:
      tags: [Payment]
      summary: 결제 요청
      operationId: requestPayment
      security:
        - bearerAuth: []
      parameters:
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            type: string
            format: uuid
          description: 멱등성 키 (클라이언트 생성 UUID)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: 결제 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '202':
          description: 결제 처리중 (비동기 확인 필요)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: 유효하지 않은 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '402':
          description: 결제 실패 (잔액 부족 등)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentErrorResponse'
        '409':
          description: 중복 결제 요청 (이미 처리됨)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'

  /payments/{paymentId}:
    parameters:
      - name: paymentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags: [Payment]
      summary: 결제 상세 조회
      operationId: getPayment
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDetailResponse'
        '403':
          description: 접근 권한 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 결제 정보 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /payments/{paymentId}/cancel:
    parameters:
      - name: paymentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
    post:
      tags: [Payment]
      summary: 결제 취소 (환불)
      operationId: cancelPayment
      security:
        - bearerAuth: []
      parameters:
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentCancelRequest'
      responses:
        '200':
          description: 취소 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: 취소 불가 (부분 환불 금액 초과 등)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '402':
          description: PG 취소 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentErrorResponse'

  /payments/{paymentId}/sync:
    parameters:
      - name: paymentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
    post:
      tags: [Payment]
      summary: 결제 상태 동기화
      description: PG사와 결제 상태를 동기화 (UNKNOWN 상태 해소)
      operationId: syncPayment
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 동기화 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404':
          description: 결제 정보 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /payments/order/{orderNumber}:
    parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [Payment]
      summary: 주문별 결제 정보 조회
      operationId: getPaymentByOrder
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDetailResponse'
        '404':
          description: 결제 정보 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PaymentMethod:
      type: string
      enum: [CARD, VIRTUAL_ACCOUNT, BANK_TRANSFER]
      description: |
        - CARD: 신용/체크카드
        - VIRTUAL_ACCOUNT: 가상계좌
        - BANK_TRANSFER: 계좌이체

    PaymentStatus:
      type: string
      enum: [PENDING, SUCCESS, FAILED, CANCELLED, PARTIAL_CANCELLED, UNKNOWN]
      description: |
        - PENDING: 결제 대기
        - SUCCESS: 결제 성공
        - FAILED: 결제 실패
        - CANCELLED: 전액 취소
        - PARTIAL_CANCELLED: 부분 취소
        - UNKNOWN: 상태 확인 필요 (PG 통신 오류)

    PaymentRequest:
      type: object
      required: [orderNumber, amount, method]
      properties:
        orderNumber:
          type: string
          description: 주문 번호
        amount:
          type: integer
          minimum: 100
          description: 결제 금액
        method:
          $ref: '#/components/schemas/PaymentMethod'
        cardNumber:
          type: string
          pattern: '^[0-9]{16}$'
          description: 카드번호 (Mock PG용, 실제로는 토큰 사용)
        cardExpiry:
          type: string
          pattern: '^(0[1-9]|1[0-2])/[0-9]{2}$'
          description: 유효기간 (MM/YY)
        cardCvc:
          type: string
          pattern: '^[0-9]{3}$'
          description: CVC

    PaymentCancelRequest:
      type: object
      required: [reason]
      properties:
        reason:
          type: string
          maxLength: 500
        cancelAmount:
          type: integer
          minimum: 100
          description: 부분 취소 금액 (미입력 시 전액 취소)

    PaymentResponse:
      type: object
      properties:
        paymentId:
          type: integer
          format: int64
        orderNumber:
          type: string
        status:
          $ref: '#/components/schemas/PaymentStatus'
        amount:
          type: integer
        cancelledAmount:
          type: integer
        method:
          $ref: '#/components/schemas/PaymentMethod'
        pgTransactionId:
          type: string
          description: PG 거래 ID
        paidAt:
          type: string
          format: date-time
        cancelledAt:
          type: string
          format: date-time

    PaymentDetailResponse:
      type: object
      properties:
        paymentId:
          type: integer
          format: int64
        orderNumber:
          type: string
        status:
          $ref: '#/components/schemas/PaymentStatus'
        amount:
          type: integer
        cancelledAmount:
          type: integer
        method:
          $ref: '#/components/schemas/PaymentMethod'
        pgTransactionId:
          type: string
        history:
          type: array
          items:
            $ref: '#/components/schemas/PaymentHistoryItem'
        createdAt:
          type: string
          format: date-time
        paidAt:
          type: string
          format: date-time
        cancelledAt:
          type: string
          format: date-time

    PaymentHistoryItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        previousStatus:
          $ref: '#/components/schemas/PaymentStatus'
        newStatus:
          $ref: '#/components/schemas/PaymentStatus'
        amount:
          type: integer
        reason:
          type: string
        pgTransactionId:
          type: string
        createdAt:
          type: string
          format: date-time

    PaymentErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        pgErrorCode:
          type: string
          description: PG사 오류 코드
        pgErrorMessage:
          type: string
          description: PG사 오류 메시지
        timestamp:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
